### ISSUE TITLE
null-safety migration please

### ISSUE THREAD

**Issue by aconitine** [coval-solutions/weight-slider#10]
Hey there!
I love weight-slider also. 
May I ask null-safety upgrade please?
Thanks a lot!

**Comment by DiogoTheCoder** [comment]
Hey @aconitine, we have that in the pipeline, will let you know!

**Comment by DiogoTheCoder** [comment]
> Hey there!
> I love weight-slider also.
> May I ask null-safety upgrade please?
> Thanks a lot!

Hey @aconitine, we have that in the pipeline, will let you know!

**Comment by DiogoTheCoder** [comment]
@aconitine we have gone ahead and upgrade our package to use null safety: 1.3.0-nullsafety (release).

https://pub.dev/packages/weight_slider/versions/1.3.0-nullsafety+1.

Cheers.
