### ISSUE TITLE
Number identifier on weight slider is blue, does not follow branding guidelines

### ISSUE THREAD

**Issue by DivTheDev** [coval-solutions/weight-slider#3]

**Comment by DiogoTheCoder** [comment]
Hi @divyesh26 👋,

Thanks for bringing this to our attention. We have committed changes which will solve this issue (https://github.com/coval-solutions/weight-slider/commit/a85fc4ded4502e7fb9438c44bda6f3e57fb6d64d), and the package on http://pub.dev/ has also been updated (https://pub.dev/packages/weight_slider/versions/1.0.2).

Cheers,

@DiogoTheCoder
