### ISSUE TITLE
How to remove paddings around weight slider

### ISSUE THREAD

**Issue by JihyeJung-Work** [coval-solutions/weight-slider#9]
Hi, I am using weight slider and I have to remove the padding around the weight slider.
I tried wrapping with container, and I could adjust the width and height, but couldn't remove the padding.
Is there a way to remove the padding?

![image](https://user-images.githubusercontent.com/65387279/107174035-95c80e80-6a0c-11eb-95af-c845fbe1dc0a.png)

I would like to remove the white space under the title...

Thanks!

**Comment by DiogoTheCoder** [comment]
Hey @JihyeJung-Work, sorry for the delay, I can investigate the issue and see what we can do.

**Comment by DiogoTheCoder** [comment]
@JihyeJung-Work Pushed an update to the package https://github.com/coval-solutions/weight-slider/releases/tag/1.2.1, see https://pub.dev/packages/weight_slider/install
